/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author ARCANGEL
 */
public class vistaInicio extends javax.swing.JFrame {

    /**
     * Creates new form vistaInicio
     */
    public vistaInicio() {
        initComponents();
        this.setExtendedState(vistaInicio.MAXIMIZED_BOTH);
        this.setTitle("RED BAYESIANA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPaneInicio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnitemAgregarNueva = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Entrada De Datos");

        mnitemAgregarNueva.setMnemonic('o');
        mnitemAgregarNueva.setText("Agregar Nueva");
        mnitemAgregarNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemAgregarNuevaActionPerformed(evt);
            }
        });
        fileMenu.add(mnitemAgregarNueva);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Procesamiento de Datos");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Ver Tabla de Datos");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        menuBar.add(editMenu);

        mnConsultas.setMnemonic('h');
        mnConsultas.setText("Consultas y/o Reportes");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Ver Tabla de Probabilidades");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        mnConsultas.add(contentMenuItem);

        menuBar.add(mnConsultas);

        mnSalir.setText("Salir");
        mnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSalirMouseClicked(evt);
            }
        });
        menuBar.add(mnSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPaneInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnitemAgregarNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemAgregarNuevaActionPerformed
        // TODO add your handling code here:
       // int numVeces = Integer.parseInt(JOptionPane.showInputDialog("Cuántas entradas realizará"))  ;
       VistaEntradaDatos vistaEntrada = new VistaEntradaDatos();
       desktopPaneInicio.add(vistaEntrada);
       vistaEntrada.toFront();
       vistaEntrada.setVisible(true);
    }//GEN-LAST:event_mnitemAgregarNuevaActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        vistaTablaDatos VistaTabla = new vistaTablaDatos();
        desktopPaneInicio.add(VistaTabla);
        VistaTabla.toFront();
        VistaTabla.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void mnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnSalirMouseClicked

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        vistaTablaProbabilidades vtp = new vistaTablaProbabilidades();
        desktopPaneInicio.add(vtp);
        vtp.toFront();
        vtp.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPaneInicio;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenu mnSalir;
    private javax.swing.JMenuItem mnitemAgregarNueva;
    // End of variables declaration//GEN-END:variables

}
